#ifndef SYS_ERROR_H
#define SYS_ERROR_H

enum sys_error {
  SYS_ALIGNMENT_ERROR,
  SYS_INVALID_ARGUMENT,
  SYS_INTERNAL_ERROR,
  SYS_MEMORY_ERROR,
  SYS_NO_ERROR,
  SYS_UNKNOWN_ERROR
};

#endif /* SYS_ERROR_H */

