#ifndef RDR_ATTRIB_H
#define RDR_ATTRIB_H

enum rdr_attrib_usage {
  RDR_ATTRIB_POSITION,
  RDR_ATTRIB_NORMAL,
  RDR_ATTRIB_COLOR,
  RDR_ATTRIB_TEXCOORD,
  RDR_ATTRIB_UNKNOWN,
  RDR_NB_ATTRIB_USAGES
};

enum rdr_type {
  RDR_FLOAT,
  RDR_FLOAT2,
  RDR_FLOAT3,
  RDR_FLOAT4,
  RDR_FLOAT4x4,
  RDR_UNKNOWN_TYPE,
  RDR_NB_TYPES
};

#endif /* RDR_ATTRIB_H */

